export const examples = [
  '1 cup stuff',
  '1 cup of stuff',
  '1/2 cup stuff',
  '1-2 cups stuff',
  '1\u20132 cups stuff',
  '1\u20142 cups stuff',
  '1 \u2013 2 cups stuff',
  '1 \u2014 2 cups stuff',
  '1 or 2 bananas',
  '1 OR 2 bananas',
  '1 to 2 cups stuff',
  '1 TO 2 cups stuff',
  '1-NaN cups stuff',
  '1 fl  oz stuff',
  '1 c stuff',
  '2 buckets of widgets\n4 oz confusion',
  '1 cup of stuff',
  '1 cup',
  'For cake',
  'Icing:',
  'a bunch of bananas',
  '2/3 cup sugar\n1 tsp baking powder',
  '2/3 cup sugar\n\n    1 tsp baking powder',
  '3 Tbsp. unsalted butter, divided',
];
