/**
 * Generates `ci/src/examples.ts` from the `parseIngredientTests` fixtures so the demo grid in
 * `ci/` can't drift from the suite. `ci/` is uploaded to StackBlitz on its own by pkg.pr.new's
 * `--template`, so it can't import the fixtures directly.
 *
 * Run with `bun run generate:ci-examples`. `src/ciExamples.test.ts` asserts the checked-in file
 * matches this output.
 */
import { parseIngredientTests } from '../src/parseIngredientTests';

/** Serializes a string with non-ASCII characters escaped, so the output is diff-friendly. */
const quote = (str: string): string =>
  `'${str
    .replaceAll('\\', '\\\\')
    .replaceAll("'", "\\'")
    .replaceAll('\n', '\\n')
    .replaceAll('\r', '\\r')
    .replaceAll(
      /[^\u0020-\u007e]/gu,
      c => `\\u${c.charCodeAt(0).toString(16).padStart(4, '0')}`
    )}'`;

const serializeInput = (input: string | string[]): string =>
  Array.isArray(input) ? `[${input.map(quote).join(', ')}]` : quote(input);

/** Source text of `ci/src/examples.ts`, derived from the fixtures. */
export const generateCIExamples = (): string => {
  const entries = Object.entries(parseIngredientTests).map(
    ([name, [input]]) => `  { name: ${quote(name)}, input: ${serializeInput(input)} },`
  );

  return `// Generated by scripts/generateCIExamples.ts from src/parseIngredientTests.ts.
// Do not edit by hand; run \`bun run generate:ci-examples\`.

export interface Example {
  /** Fixture name. */
  name: string;
  /** Ingredient list, as passed to \`parseIngredient\`. */
  input: string | string[];
}

export const examples: Example[] = [
${entries.join('\n')}
];
`;
};

if (import.meta.main) {
  await Bun.write(new URL('../ci/src/examples.ts', import.meta.url), generateCIExamples());
}
